In [2]:
import numpy as np
import math

a = np.array([1,2,3])
b = np.array([[2,2,2],[3,3,3]])
print(a)
print(b)
print(a.ndim)
print(b.ndim)

[1 2 3]
[[2 2 2]
 [3 3 3]]
1
2


In [4]:
print(b.shape)

(2, 3)


In [5]:
a.dtype

dtype('int64')

In [6]:
b.dtype.name

'int64'

In [7]:
d = np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
c = np.ones((3,4))

In [9]:
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
e = np.random.rand(2,3)    # to generate random array
print(e)

[[0.72231066 0.61396354 0.28521768]
 [0.48518065 0.43983942 0.15296884]]


In [12]:
f = np.arange(10, 50 ,2)           # to creat a range between first and second with space count of third
print(f)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [13]:
g = np.linspace(2 , 3 , 15)        # to generate a float series between first and second by number of third counts
print(g)

[2.         2.07142857 2.14285714 2.21428571 2.28571429 2.35714286
 2.42857143 2.5        2.57142857 2.64285714 2.71428571 2.78571429
 2.85714286 2.92857143 3.        ]


In [14]:
feranheit = np.array([2,-5,-3,5])
celcius = (feranheit - 31) * (5/9)
print(celcius)

[-16.11111111 -20.         -18.88888889 -14.44444444]


In [15]:
celcius > -20 

array([ True, False,  True,  True])

In [16]:
celcius %2 == 0  # check if they are even

array([False,  True, False, False])

In [17]:
A= np.array([[1,0],[1,1]])
B= np.array([[2,1],[3,4]])

print(A*B)    # for elementwise

print(A@B)    # for Matrix product - dot function

[[2 0]
 [3 4]]
[[2 1]
 [5 5]]


In [19]:
array3 = np.array([2.6,32,9.1,3,3.2,4.1,.5])

print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

54.50000000000001
32.0
0.5
7.7857142857142865


In [22]:
x = np.arange(1,16,1).reshape(3,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])